---
framework: mocha
preRun:
     command:
        - yarn install --frozen-lockfile --non-interactive
preMerge:
  pattern:
    - "./node-tests/blueprints/**/*-test.js"
postMerge:
  pattern: 
    - "./node-tests/blueprints/**/*-test.js"
postRun:
     command:
        - yarn --version
version: 1.0
