name: CI

on:
  push:
    branches:
      - master
      - beta
      - release
      # release branches
      - release*
      - lts*
      # nightly ci cron branches
      - cron*
    tags:
      - 'v*'
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: linting
        run: yarn lint

  blueprint-test:
    name: Blueprint Tests
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: test
        run: yarn test:blueprints

